version: '3.8'

services:
  supabase-mcp:
    build: .
    container_name: supabase-mcp-server
    ports:
      - "3456:3000"  # HTTP/SSE endpoint
    environment:
      - SUPABASE_ACCESS_TOKEN=${SUPABASE_ACCESS_TOKEN}
      - PORT=3000
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - mcp-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  mcp-network:
    driver: bridge